AWSTemplateFormatVersion: 2010-09-09
## =================== DESCRIPTION =================== ##
Description: ---
  AWS CloudFormation S3 bucket template
  - Create a new S3 bucket without policy
Parameters: 
  paramS3Name:
    Description: Name of s3 bucket
    Type: String
    Default: 'test-s3bucket-using-iac'
Resources: 
  mytestings3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete #allow CloudFormation delete the bucket when stack is deleted
    Properties:
      BucketName: !Ref paramS3Name
      Tags:
        - Key: 'name'
          Value: 'testing-bucket'
Outputs:
  bucketName:
    Value: !Ref mytestings3Bucket
    Description: my testing bucket description