AWSTemplateFormatVersion: 2010-09-09
## =================== DESCRIPTION =================== ##
Description: ---
  AWS CloudFormation S3 bucket template
  - Create a new S3 bucket without policy
Parameters: 
  paramS3Name:
    Description: 
    Type: AWS::EC2::Instance::Id
    Default: test-s3bucket-using-iac
Resources: 
  mytestings3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref paramS3Name
      Tags:
        - Key: 'name'
          Value: 'testing-bucket'
Outputs:
  outputWebsiteURL:
    Value: !GetAtt
      - mytestings3Bucket
    Description: Static website URL